baseURL = 'https://dneto.me/'
title = 'dneto.me'
summaryLength = 100
defaultContentLanguage = 'pt'
languageCode = 'pt-BR'

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.extensions]
footnote = true

[markup.tableOfContents]
endLevel = 4
ordered = true

[taxonomies]
tag = 'tags'

[languages.en]
contentDir = 'content/en'
languageName = 'English'
[languages.pt]
contentDir = 'content/pt'
languageName = 'Português'
