baseURL = 'https://dneto.me/'
defaultContentLanguage = 'pt'
languageCode = 'pt-BR'
title = 'dneto.me'
summaryLength = 100

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.extensions]
footnote = true

[markup.tableOfContents]
endLevel=4
ordered=true

[taxonomies]
tag = 'tags'
