baseURL = 'https://dneto.me/'
defaultContentLanguage = 'pt'
languageCode = 'pt-BR'
title = 'dneto.me'
summaryLength = 150

[markup]
[markup.highlight]
style = 'catppuccin-mocha'

[markup.goldmark]
[markup.goldmark.extensions]
footnote = true
